-- ============================================================
-- STAGING TERMINAL BUNDLE (generated by tools/build-staging-bundle.js - do not edit by hand)
-- Paste this WHOLE file into the NEW (staging) Supabase project: SQL Editor > New query > Run.
-- Before running: create the terminal Auth user (Authentication > Users > Add user):
--     email:    terminal@test.dawam.arwaenterprises.com      password: test-terminal-key-1234      tick "Auto Confirm User"
-- Contains migrations 004 and 005. Needs 001-003 (staging-security-bundle.sql + 003) already applied. Safe to run again. NEVER run on the live project.
-- ============================================================

-- ============================================================
-- Migration 004: the punch terminal gets its own identity and ONLY narrow functions (ROADMAP S3; finding 59)
-- ============================================================
-- Run AFTER 001-003. Tested on local Postgres (tests/db). NOT yet applied to any Supabase project.
--
-- The terminal (tablet at the gate) signs in like a user, but as the role "terminal" of one company:
--     email  terminal@<company code>.dawam.arwaenterprises.com   password = the TERMINAL KEY
-- A terminal can NOT read or change any table directly. It can only call the terminal_* functions below, which return
-- exactly what a terminal needs (never salaries, ID numbers or other staff data).
-- Admins/supervisors keep their access; their table rules now also check the role.
-- ============================================================

-- 1. a new role value
alter table public.users drop constraint if exists users_role_check;
alter table public.users add constraint users_role_check check (role = any (array['super_admin', 'admin', 'supervisor', 'terminal']));

-- 2. role helpers
create or replace function public.is_staff()
returns boolean language sql stable security definer set search_path = public as $$
    select coalesce(public.current_user_role() in ('admin', 'supervisor', 'super_admin'), false)
$$;
create or replace function public.require_terminal()
returns uuid language plpgsql stable security definer set search_path = public as $$
declare v uuid := public.current_client_id();
begin
    if v is null or public.current_user_role() is distinct from 'terminal' then
        raise exception 'not allowed' using errcode = '42501';
    end if;
    return v;
end;
$$;
revoke all on function public.is_staff(), public.require_terminal() from public, anon;
grant execute on function public.is_staff(), public.require_terminal() to authenticated;

-- 3. table rules: only staff (admin / supervisor), never the terminal
do $$
declare t text;
begin
    foreach t in array array['departments','laborers','punch_locations','punch_records','daily_attendance','lop_requests','settings',
        'attendance_freeze','holidays','ot_rates','overtime_records','iqama_registry','enrollment_links']
    loop
        execute format('drop policy if exists %I on public.%I', 'tenant ' || t, t);
        execute format('create policy %I on public.%I for all to authenticated
                        using (client_id = (select public.current_client_id()) and (select public.is_staff()))
                        with check (client_id = (select public.current_client_id()) and (select public.is_staff()))', 'tenant ' || t, t);
    end loop;
end $$;
drop policy if exists "tenant audit_log select" on public.audit_log;
drop policy if exists "tenant audit_log insert" on public.audit_log;
create policy "tenant audit_log select" on public.audit_log for select to authenticated using (client_id = (select public.current_client_id()) and (select public.is_staff()));
create policy "tenant audit_log insert" on public.audit_log for insert to authenticated with check (client_id = (select public.current_client_id()) and (select public.is_staff()));

-- 4. attendance recalculation: an internal worker + the public wrapper (same maths as before)
create or replace function public._recalc_attendance(p_client uuid, p_labor_id text, p_date date)
returns void language plpgsql security definer set search_path = public as $$
declare
    v_department_id uuid;
    v_first_login time;
    v_last_logout time;
    v_total_hours numeric;
    v_total_minutes integer;
    v_auto_status text;
    v_min_present_minutes integer := 570;
    v_min_half_minutes integer := 240;
    v_dept_min_hours text;
begin
    select department_id into v_department_id from laborers where labor_id = p_labor_id and client_id = p_client limit 1;
    if v_department_id is null then return; end if;

    select min(time), max(time) into v_first_login, v_last_logout
    from punch_records where labor_id = p_labor_id and date = p_date and client_id = p_client;
    if v_first_login is null then return; end if;

    select min_hours_full_day into v_dept_min_hours from departments where id = v_department_id limit 1;
    if v_dept_min_hours is not null then
        v_min_present_minutes := extract(hour from v_dept_min_hours::time) * 60 + extract(minute from v_dept_min_hours::time);
    end if;

    v_total_minutes := extract(epoch from (v_last_logout - v_first_login)) / 60;
    v_total_hours   := v_total_minutes / 60.0;
    if v_total_minutes >= v_min_present_minutes then v_auto_status := 'P';
    elsif v_total_minutes >= v_min_half_minutes then v_auto_status := 'H';
    else v_auto_status := 'A'; end if;

    insert into daily_attendance (labor_id, department_id, date, first_login, last_logout, total_hours, auto_status, final_status, client_id, updated_at)
    values (p_labor_id, v_department_id, p_date, v_first_login, v_last_logout, v_total_hours, v_auto_status, v_auto_status, p_client, now())
    on conflict (labor_id, date) do update set
        first_login = excluded.first_login, last_logout = excluded.last_logout, total_hours = excluded.total_hours,
        auto_status = excluded.auto_status,
        final_status = case when daily_attendance.final_status in ('LP','LH','LA') then daily_attendance.final_status else excluded.auto_status end,
        updated_at = now();
end;
$$;
revoke all on function public._recalc_attendance(uuid, text, date) from public, anon, authenticated;

create or replace function public.update_daily_attendance(p_labor_id text, p_date date)
returns void language plpgsql security definer set search_path = public as $$
declare
    v_caller uuid := public.current_client_id();
    v_client uuid;
begin
    select client_id into v_client from laborers where labor_id = p_labor_id limit 1;
    if v_client is null then return; end if;
    if v_caller is null or v_caller <> v_client or public.current_user_role() not in ('admin', 'supervisor', 'super_admin', 'terminal') then
        raise exception 'not allowed' using errcode = '42501';
    end if;
    perform public._recalc_attendance(v_client, p_labor_id, p_date);
end;
$$;
-- staff only (a terminal must not consume labor ids or register ID numbers)
create or replace function public.get_next_labor_id()
returns text language plpgsql security definer set search_path = public as $$
declare next_id integer;
begin
    if public.current_client_id() is null or not public.is_staff() then raise exception 'not allowed' using errcode = '42501'; end if;
    update labor_id_sequence set next_value = next_value + 1 where id = 1 returning next_value - 1 into next_id;
    return 'L' || next_id::text;
end;
$$;
create or replace function public.register_iqama(p_iqama text)
returns text language plpgsql security definer set search_path = public as $$
declare
    v_client uuid := public.current_client_id();
    existing_labor_id text;
    new_labor_id text;
begin
    if v_client is null or not public.is_staff() then raise exception 'not allowed' using errcode = '42501'; end if;
    select labor_id into existing_labor_id from iqama_registry where iqama_number = p_iqama and client_id = v_client;
    if existing_labor_id is not null then return existing_labor_id; end if;
    new_labor_id := public.get_next_labor_id();
    insert into iqama_registry (iqama_number, labor_id, client_id) values (p_iqama, new_labor_id, v_client);
    return new_labor_id;
end;
$$;

-- 5. THE TERMINAL FUNCTIONS
-- 5a. everything the terminal keeps for offline use, in one call (no salaries, no ID numbers)
create or replace function public.terminal_bootstrap()
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare v uuid := public.require_terminal();
begin
    return jsonb_build_object(
        'client', (select jsonb_build_object('id', c.id, 'client_code', c.client_code, 'business_name', c.business_name, 'subscribed_apps', c.subscribed_apps)
                   from clients c where c.id = v),
        'settings', (select coalesce(jsonb_object_agg(s.key, s.value), '{}'::jsonb) from settings s where s.client_id = v),
        'locations', (select coalesce(jsonb_agg(to_jsonb(l) order by l.name), '[]'::jsonb) from punch_locations l where l.client_id = v and l.status = 'active'),
        'laborers', (select coalesce(jsonb_agg(jsonb_build_object('labor_id', b.labor_id, 'name', b.name, 'department_id', b.department_id,
                        'face_descriptor', b.face_descriptor, 'face_enrolled', b.face_enrolled) order by b.labor_id), '[]'::jsonb)
                     from laborers b where b.client_id = v and b.status = 'active' and b.face_enrolled)
    );
end;
$$;

-- 5b. punches of one labor on one day (for the "my punches" screen)
create or replace function public.terminal_today_punches(p_labor_id text, p_date date)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare v uuid := public.require_terminal();
begin
    return coalesce((select jsonb_agg(jsonb_build_object('id', r.id, 'type', r.type, 'time', r.time, 'date', r.date,
                    'location_name', r.location_name, 'photo_url', r.photo_url, 'created_at', r.created_at) order by r.created_at)
                    from punch_records r where r.client_id = v and r.labor_id = p_labor_id and r.date = p_date), '[]'::jsonb);
end;
$$;

-- 5c. how many punches today, the daily limit, and the last punch type (decides the next type and the limit)
create or replace function public.terminal_punch_state(p_labor_id text, p_date date)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare v uuid := public.require_terminal();
begin
    return jsonb_build_object(
        'count', (select count(*) from punch_records where client_id = v and labor_id = p_labor_id and date = p_date),
        'max', coalesce((select nullif(value, '')::int from settings where client_id = v and key = 'max_punches_per_day'), 999),
        'last_type', (select type from punch_records where client_id = v and labor_id = p_labor_id and date = p_date order by time desc limit 1)
    );
end;
$$;

-- 5d. record one punch (online, or an offline punch being uploaded). Same rules the app had, now decided by the database:
--     night-shift date correction (settings night_shift_start/end), duplicates ignored, attendance recalculated.
create or replace function public.terminal_record_punch(p jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
    v_client uuid := public.require_terminal();
    v_labor_id text := p ->> 'labor_id';
    v_labor record;
    v_date date;
    v_time time;
    v_type text := p ->> 'type';
    v_night_start int := 20 * 60;
    v_night_end int := 6 * 60 + 30;
    v_val text;
    v_mins int;
    v_prev date;
    v_final_date date;
    v_is_night_end boolean := false;
    v_location uuid := null;
    v_conf int := null;
    v_photo text := nullif(p ->> 'photo_url', '');
    v_id uuid;
    v_existing uuid;
begin
    select * into v_labor from laborers where client_id = v_client and labor_id = v_labor_id and status = 'active';
    if not found then raise exception 'unknown or inactive labor' using errcode = 'P0001'; end if;
    if v_type is null or v_type not in ('login', 'logout') then raise exception 'invalid punch type' using errcode = 'P0001'; end if;
    begin
        v_date := (p ->> 'date')::date;
        v_time := (p ->> 'time')::time;
    exception when others then raise exception 'invalid date or time' using errcode = 'P0001'; end;
    if v_date is null or v_time is null or v_date < current_date - 31 or v_date > current_date + 1 then
        raise exception 'date out of range' using errcode = 'P0001';
    end if;
    if p ->> 'location_id' is not null then
        select id into v_location from punch_locations where id = (p ->> 'location_id')::uuid and client_id = v_client;
    end if;
    if p ->> 'confidence' is not null then v_conf := greatest(0, least(100, (p ->> 'confidence')::int)); end if;
    if v_photo is not null and length(v_photo) > 500 then raise exception 'photo link too long' using errcode = 'P0001'; end if;

    select value into v_val from settings where client_id = v_client and key = 'night_shift_start';
    if v_val ~ '^\d{1,2}:\d{2}' then v_night_start := split_part(v_val, ':', 1)::int * 60 + split_part(v_val, ':', 2)::int; end if;
    select value into v_val from settings where client_id = v_client and key = 'night_shift_end';
    if v_val ~ '^\d{1,2}:\d{2}' then v_night_end := split_part(v_val, ':', 1)::int * 60 + split_part(v_val, ':', 2)::int; end if;

    v_final_date := v_date;
    v_mins := extract(hour from v_time)::int * 60 + extract(minute from v_time)::int;
    if v_mins <= v_night_end then
        v_prev := v_date - 1;
        if exists (select 1 from punch_records where client_id = v_client and labor_id = v_labor_id and date = v_prev
                   and extract(hour from time)::int * 60 + extract(minute from time)::int >= v_night_start) then
            v_final_date := v_prev; v_is_night_end := true;
        end if;
    end if;

    select id into v_existing from punch_records where client_id = v_client and labor_id = v_labor_id and date = v_final_date and time = v_time limit 1;
    if v_existing is not null then
        return jsonb_build_object('success', true, 'duplicate', true, 'id', v_existing, 'date', v_final_date);
    end if;

    insert into punch_records (labor_id, department_id, date, time, type, location_id, location_name, confidence, photo_url, client_id, is_night_shift_end)
    values (v_labor_id, v_labor.department_id, v_final_date, v_time, v_type, v_location, left(p ->> 'location_name', 200), v_conf, v_photo, v_client, v_is_night_end)
    returning id into v_id;

    update laborers set last_sync_at = now() where id = v_labor.id;
    perform public._recalc_attendance(v_client, v_labor_id, v_final_date);
    return jsonb_build_object('success', true, 'duplicate', false, 'id', v_id, 'date', v_final_date, 'is_night_shift_end', v_is_night_end);
end;
$$;

-- 5e. a face that matched badly: count it, flag for re-enrollment after 3 in a week (same rule as before)
create or replace function public.terminal_low_confidence(p_labor_id text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
    v uuid := public.require_terminal();
    v_labor record;
    v_new int;
    v_needs boolean;
begin
    select * into v_labor from laborers where client_id = v and labor_id = p_labor_id and status = 'active';
    if not found then raise exception 'unknown or inactive labor' using errcode = 'P0001'; end if;
    v_new := coalesce(v_labor.low_confidence_count, 0) + 1;
    if v_labor.last_low_confidence_date is not null and (current_date - v_labor.last_low_confidence_date) > 7 then v_new := 1; end if;
    v_needs := v_new >= 3;
    update laborers set low_confidence_count = v_new, last_low_confidence_date = current_date, needs_reenrollment = v_needs where id = v_labor.id;
    return jsonb_build_object('success', true, 'needs_reenrollment', v_needs);
end;
$$;

revoke all on function public.update_daily_attendance(text, date), public.get_next_labor_id(), public.register_iqama(text),
    public.terminal_bootstrap(), public.terminal_today_punches(text, date), public.terminal_punch_state(text, date),
    public.terminal_record_punch(jsonb), public.terminal_low_confidence(text) from public, anon;
grant execute on function public.update_daily_attendance(text, date), public.get_next_labor_id(), public.register_iqama(text),
    public.terminal_bootstrap(), public.terminal_today_punches(text, date), public.terminal_punch_state(text, date),
    public.terminal_record_punch(jsonb), public.terminal_low_confidence(text) to authenticated;

-- 6. platform-owner command: link a company's terminal login (Authentication > Users > Add user, email below, password = the terminal key)
--    Usage (SQL editor):  select public.link_terminal_profile('TEST');
create or replace function public.link_terminal_profile(p_client_code text, p_name text default 'Punch Terminal')
returns text language plpgsql security definer set search_path = public, auth as $$
declare
    v_client uuid;
    v_email  text;
    v_auth   uuid;
begin
    select id into v_client from public.clients where upper(client_code) = upper(btrim(p_client_code));
    if v_client is null then raise exception 'unknown company code: %', p_client_code; end if;
    v_email := 'terminal@' || lower(btrim(p_client_code)) || '.dawam.arwaenterprises.com';
    select id into v_auth from auth.users where lower(email) = v_email;
    if v_auth is null then raise exception 'create the Auth account first (Authentication > Users > Add user) with email: %', v_email; end if;
    update public.users set auth_id = v_auth, status = 'active', role = 'terminal' where client_id = v_client and username = 'terminal';
    if not found then
        insert into public.users (username, name, role, status, client_id, auth_id) values ('terminal', p_name, 'terminal', 'active', v_client, v_auth);
    end if;
    return v_email;
end;
$$;
revoke all on function public.link_terminal_profile(text, text) from public, anon, authenticated;

-- 7. photos: the old open storage rules (staging only) go; a terminal may ADD photos, nobody else can through the public key.
--    (Photos are still in a public bucket; step S4 makes them private and company-separated.)
drop policy if exists "tmp punch-photos select" on storage.objects;
drop policy if exists "tmp punch-photos insert" on storage.objects;
drop policy if exists "tmp punch-photos delete" on storage.objects;
drop policy if exists "terminal adds punch photos" on storage.objects;
create policy "terminal adds punch photos" on storage.objects for insert to authenticated
    with check (bucket_id = 'punch-photos' and public.current_user_role() = 'terminal');

-- ============================================================
-- Changelog
-- 2026-10-02  004  Written and tested locally. Not applied to any Supabase project yet.
-- ============================================================

-- ============================================================
-- Migration 005: a terminal cannot read the company row (ROADMAP S3 hardening)
-- ============================================================
-- Found by the end-to-end terminal test on staging: the rule "you may read your own company row" (migration 001) also let a
-- terminal read its company's contact and subscription details. A terminal does not need them (it gets the company name and code
-- through terminal_bootstrap), so only staff (admin / supervisor) may read the company row now.
drop policy if exists "own client row" on public.clients;
create policy "own client row" on public.clients for select to authenticated
    using (id = (select public.current_client_id()) and (select public.is_staff()));

-- ---------- link the staging test terminal (the Auth user above must exist) ----------
select public.link_terminal_profile('TEST') as linked_terminal_email;
