-- ============================================================
-- STAGING SECURITY BUNDLE (generated by tools/build-staging-bundle.js - do not edit by hand)
-- Paste this WHOLE file into the NEW (staging) Supabase project: SQL Editor > New query > Run.
-- Before running: create the Auth user (Authentication > Users > Add user):
--     email:    admin@test.dawam.arwaenterprises.com      password: Test@1234      tick "Auto Confirm User"
-- NEVER run on the live project.
-- ============================================================

-- ============================================================
-- Migration 001: security foundation (ROADMAP tasks 29-31, 43-45)
-- ============================================================
-- Replaces the temporary "allow all" access with real tenant isolation:
--   * a logged-in user (Supabase Auth) sees and changes ONLY the rows of their own client
--   * the public (anon) key can no longer read or write any table directly
--   * password hashes are no longer readable, clients cannot edit their own subscription
--
-- Run order on a project:  schema.sql  ->  (policies-temporary-open.sql, staging only)  ->  001 (this file)
-- DO NOT apply to a project whose app still uses the old login (app would stop working).
-- Tested on local Postgres 16 with stand-ins for Supabase's auth schema: tests/db/ (run: bash tests/db/run.sh).
-- NOT yet applied to any Supabase project.
-- ============================================================

-- 1. Link our users table to Supabase Auth users
alter table public.users add column if not exists auth_id uuid unique references auth.users(id) on delete cascade;

-- 2. Who is the caller? Resolved from the Auth session (auth.uid()), never from anything the browser sends.
create or replace function public.current_client_id()
returns uuid language sql stable security definer set search_path = public as $$
    select client_id from public.users where auth_id = auth.uid() and status = 'active' limit 1
$$;
create or replace function public.current_user_role()
returns text language sql stable security definer set search_path = public as $$
    select role from public.users where auth_id = auth.uid() and status = 'active' limit 1
$$;
revoke all on function public.current_client_id(), public.current_user_role() from public, anon;
grant execute on function public.current_client_id(), public.current_user_role() to authenticated;

-- 3. Close the public (anon) door completely; later steps give the punch terminal its own narrow functions
revoke all on all tables    in schema public from anon;
revoke all on all sequences in schema public from anon;
revoke all on all functions in schema public from anon;
alter default privileges in schema public revoke all on tables    from anon;
alter default privileges in schema public revoke all on functions from anon;

-- 4. Remove the temporary open policies (created by policies-temporary-open.sql, if present)
do $$
declare r record;
begin
    for r in select policyname, tablename from pg_policies where schemaname = 'public' and policyname like 'tmp allow all %' loop
        execute format('drop policy %I on public.%I', r.policyname, r.tablename);
    end loop;
end $$;

-- 5. Row level security ON for every attendance table (including the three that had it OFF)
do $$
declare t text;
begin
    foreach t in array array['clients','users','departments','laborers','punch_locations','punch_records','daily_attendance',
        'lop_requests','audit_log','settings','labor_id_sequence','attendance_freeze','holidays','ot_rates','overtime_records',
        'iqama_registry','enrollment_links']
    loop execute format('alter table public.%I enable row level security', t); end loop;
end $$;

-- 6. Tenant tables: full access, but ONLY to rows of the caller's own client
do $$
declare t text;
begin
    foreach t in array array['departments','laborers','punch_locations','punch_records','daily_attendance','lop_requests','settings',
        'attendance_freeze','holidays','ot_rates','overtime_records','iqama_registry','enrollment_links']
    loop
        execute format('drop policy if exists %I on public.%I', 'tenant ' || t, t);
        execute format('create policy %I on public.%I for all to authenticated
                        using (client_id = (select public.current_client_id()))
                        with check (client_id = (select public.current_client_id()))', 'tenant ' || t, t);
        execute format('grant select, insert, update, delete on public.%I to authenticated', t);
        -- a row created without an explicit client_id belongs to the caller's client (no more hard-coded default client)
        execute format('alter table public.%I alter column client_id set default public.current_client_id()', t);
    end loop;
end $$;

-- 7. audit_log: add and read your own client's entries, never change or delete them
drop policy if exists "tenant audit_log select" on public.audit_log;
drop policy if exists "tenant audit_log insert" on public.audit_log;
create policy "tenant audit_log select" on public.audit_log for select to authenticated using (client_id = (select public.current_client_id()));
create policy "tenant audit_log insert" on public.audit_log for insert to authenticated with check (client_id = (select public.current_client_id()));
grant select, insert on public.audit_log to authenticated;
alter table public.audit_log alter column client_id set default public.current_client_id();

-- 8. users: you can read your OWN row, never anyone else's, and never the password hash column
drop policy if exists "own user row" on public.users;
create policy "own user row" on public.users for select to authenticated using (auth_id = auth.uid());
revoke all on public.users from authenticated;
grant select (id, username, name, role, department_id, status, created_at, updated_at, client_id, permissions, auth_id) on public.users to authenticated;

-- 9. clients: read your own company row only; nobody can change subscription data from the app
drop policy if exists "own client row" on public.clients;
create policy "own client row" on public.clients for select to authenticated using (id = (select public.current_client_id()));
revoke all on public.clients from authenticated;
grant select on public.clients to authenticated;

-- 10. labor_id_sequence: only the functions below touch it (no direct access)
revoke all on public.labor_id_sequence from authenticated;

-- 11. functions: run with fixed search_path, check the caller's client, not callable by the public key
create or replace function public.get_next_labor_id()
returns text language plpgsql security definer set search_path = public as $$
declare next_id integer;
begin
    if public.current_client_id() is null then raise exception 'not allowed' using errcode = '42501'; end if;
    update labor_id_sequence set next_value = next_value + 1 where id = 1 returning next_value - 1 into next_id;
    return 'L' || next_id::text;
end;
$$;

create or replace function public.register_iqama(p_iqama text)
returns text language plpgsql security definer set search_path = public as $$
declare
    v_client uuid := public.current_client_id();
    existing_labor_id text;
    new_labor_id text;
begin
    if v_client is null then raise exception 'not allowed' using errcode = '42501'; end if;
    select labor_id into existing_labor_id from iqama_registry where iqama_number = p_iqama and client_id = v_client;
    if existing_labor_id is not null then return existing_labor_id; end if;
    new_labor_id := public.get_next_labor_id();
    insert into iqama_registry (iqama_number, labor_id, client_id) values (p_iqama, new_labor_id, v_client);
    return new_labor_id;
end;
$$;

-- same calculation as before; only the caller check and fixed search_path are new
create or replace function public.update_daily_attendance(p_labor_id text, p_date date)
returns void language plpgsql security definer set search_path = public as $$
declare
    v_caller uuid := public.current_client_id();
    v_client_id uuid;
    v_department_id uuid;
    v_first_login time;
    v_last_logout time;
    v_total_hours numeric;
    v_total_minutes integer;
    v_auto_status text;
    v_min_present_minutes integer := 570;
    v_min_half_minutes integer := 240;
    v_dept_min_hours text;
begin
    select client_id, department_id into v_client_id, v_department_id from laborers where labor_id = p_labor_id limit 1;
    if v_client_id is null then return; end if;
    if v_caller is null or v_caller <> v_client_id then raise exception 'not allowed' using errcode = '42501'; end if;

    select min(time), max(time) into v_first_login, v_last_logout
    from punch_records where labor_id = p_labor_id and date = p_date and client_id = v_client_id;
    if v_first_login is null then return; end if;

    select min_hours_full_day into v_dept_min_hours from departments where id = v_department_id limit 1;
    if v_dept_min_hours is not null then
        v_min_present_minutes := extract(hour from v_dept_min_hours::time) * 60 + extract(minute from v_dept_min_hours::time);
    end if;

    v_total_minutes := extract(epoch from (v_last_logout - v_first_login)) / 60;
    v_total_hours   := v_total_minutes / 60.0;
    if v_total_minutes >= v_min_present_minutes then v_auto_status := 'P';
    elsif v_total_minutes >= v_min_half_minutes then v_auto_status := 'H';
    else v_auto_status := 'A'; end if;

    insert into daily_attendance (labor_id, department_id, date, first_login, last_logout, total_hours, auto_status, final_status, client_id, updated_at)
    values (p_labor_id, v_department_id, p_date, v_first_login, v_last_logout, v_total_hours, v_auto_status, v_auto_status, v_client_id, now())
    on conflict (labor_id, date) do update set
        first_login = excluded.first_login, last_logout = excluded.last_logout, total_hours = excluded.total_hours,
        auto_status = excluded.auto_status,
        final_status = case when daily_attendance.final_status in ('LP','LH','LA') then daily_attendance.final_status else excluded.auto_status end,
        updated_at = now();
end;
$$;

revoke all on function public.get_next_labor_id(), public.register_iqama(text), public.update_daily_attendance(text, date) from public, anon;
grant execute on function public.get_next_labor_id(), public.register_iqama(text), public.update_daily_attendance(text, date) to authenticated;
-- the old helper that read settings without any client check is not used by the app: keep it away from the public key
revoke all on function public.calculate_attendance_status(numeric) from public, anon;

-- ============================================================
-- Changelog
-- 2026-10-02  001  Written and tested locally (tests/db). Not applied to any Supabase project yet.
-- ============================================================

-- ============================================================
-- Migration 002: login through Supabase Auth, one admin per client (ROADMAP S2; tasks 14, 26, 47)
-- ============================================================
-- Run AFTER 001. Tested on local Postgres (tests/db). NOT yet applied to any Supabase project.
--
-- How login works after this:
--   * the app signs in with Supabase Auth using the email  <username>@<company code>.dawam.arwaenterprises.com  and the password
--     (the person still types Company code + Username + Password; the email is built by the app, nothing is ever sent to it)
--   * an Auth account only gets access to data once it is LINKED to a company with  public.link_admin_profile(...)
--     (run by the platform owner in the SQL editor). Nobody can link themselves, so even if public sign-up were left on,
--     a stranger who registers an address would see nothing.
-- ============================================================

-- 1. passwords now live in Supabase Auth, not in our table
alter table public.users alter column password_hash drop not null;

-- 2. a username only has to be unique inside its company (two companies can both have "admin")
alter table public.users drop constraint if exists users_username_key;
alter table public.users add constraint users_client_username_key unique (client_id, username);

-- 3. exactly one ACTIVE admin per company (to replace an admin: set the old one inactive, then add the new one)
--    If this fails on an existing database, that company has several active admins: decide who stays, then re-run.
create unique index if not exists users_one_admin_per_client on public.users (client_id) where role = 'admin' and status = 'active';

-- 4. settings: unique per company + key (was: key alone, so two companies could not both have "night_shift_start")
alter table public.settings alter column client_id set not null;
alter table public.settings drop constraint if exists settings_pkey;
alter table public.settings add primary key (client_id, key);

-- 5. a company that is deactivated or whose subscription ended gets no data access at all (enforced here, not only in the app)
create or replace function public.current_client_id()
returns uuid language sql stable security definer set search_path = public as $$
    select u.client_id
    from public.users u join public.clients c on c.id = u.client_id
    where u.auth_id = auth.uid()
      and u.status = 'active'
      and c.is_active
      and c.subscription_status is distinct from 'expired'
      and (c.subscription_status = 'premium' or c.subscription_end_date is null or c.subscription_end_date >= current_date)
    limit 1
$$;
create or replace function public.current_user_role()
returns text language sql stable security definer set search_path = public as $$
    select u.role
    from public.users u join public.clients c on c.id = u.client_id
    where u.auth_id = auth.uid() and u.status = 'active' and c.is_active
      and c.subscription_status is distinct from 'expired'
      and (c.subscription_status = 'premium' or c.subscription_end_date is null or c.subscription_end_date >= current_date)
    limit 1
$$;

-- 6. platform-owner command: link an Auth account to a company (creates the admin profile, or links an existing one)
--    Usage (SQL editor):  select public.link_admin_profile('TEST', 'admin', 'Test Admin');
--    The Auth account (Authentication > Users > Add user) must exist first, with email  admin@test.dawam.arwaenterprises.com
create or replace function public.link_admin_profile(p_client_code text, p_username text, p_name text default null)
returns text language plpgsql security definer set search_path = public, auth as $$
declare
    v_client uuid;
    v_email  text;
    v_auth   uuid;
    v_user   text := lower(btrim(p_username));
begin
    select id into v_client from public.clients where upper(client_code) = upper(btrim(p_client_code));
    if v_client is null then raise exception 'unknown company code: %', p_client_code; end if;
    v_email := v_user || '@' || lower(btrim(p_client_code)) || '.dawam.arwaenterprises.com';
    select id into v_auth from auth.users where lower(email) = v_email;
    if v_auth is null then raise exception 'create the Auth account first (Authentication > Users > Add user) with email: %', v_email; end if;

    update public.users set auth_id = v_auth, status = 'active' where client_id = v_client and username = v_user;
    if not found then
        insert into public.users (username, name, role, status, client_id, auth_id)
        values (v_user, coalesce(p_name, p_username), 'admin', 'active', v_client, v_auth);
    end if;
    return v_email;
end;
$$;
revoke all on function public.link_admin_profile(text, text, text) from public, anon, authenticated;

-- ============================================================
-- Changelog
-- 2026-10-02  002  Written and tested locally. Not applied to any Supabase project yet.
-- ============================================================

-- ---------- link the staging test admin (the Auth user above must exist) ----------
select public.link_admin_profile('TEST', 'admin', 'Test Admin') as linked_login_email;
