-- ============================================================
-- LIVE CUTOVER BUNDLE (generated by tools/build-live-bundle.js - do not edit by hand)
-- Run ONLY on the LIVE project (address contains kyktwzwiraipwyglkhva), ONLY in the planned window, AFTER the preparation steps in
-- supabase/CUTOVER_PLAN.md (Auth accounts created). It moves the other apps' tables to the schema "archive_other_apps" (nothing is deleted),
-- deletes AE2/AE3, unused punch locations and retired supervisors (cleanup, NOT undone by the rollback), applies all security rules, makes the photo bucket private.
-- Rollback: supabase/live/live-rollback-bundle.sql
-- ============================================================

-- >>>>>>>>>> live/000_prepare_live.sql
-- ============================================================
-- LIVE 000: prepare the LIVE project for the attendance-only security rules (ROADMAP S5)
-- ============================================================
-- Run ONLY on the LIVE project (address contains kyktwzwiraipwyglkhva), as the first part of live-cutover-bundle.sql, in the planned window.
-- Written from the real structure of the live project (export of 2026-10-02). Tested on a local copy that imitates it (tests/db/live-like.*).
-- NOTHING IS DELETED by this file:
--   * the pharmacy, expense and admin tables are MOVED to a separate schema "archive_other_apps" (not reachable through the app's public API).
--     To restore one:  alter table archive_other_apps.<name> set schema public;
--     To delete them for good (only when you are sure):  drop schema archive_other_apps cascade;
--   * the old "allow everything" rules are removed (the new rules replace them),
--   * the supervisors are set to inactive (kept for history; they have no new login, so they cannot sign in).
-- ============================================================

-- 0. safety: this must look like the live attendance project
do $$ begin
    if to_regclass('public.laborers') is null or to_regclass('public.punch_records') is null or to_regclass('public.clients') is null then
        raise exception 'This does not look like the attendance database (laborers / punch_records / clients missing). Stopping.';
    end if;
end $$;

-- 1. other apps: move their tables out of the public API
create schema if not exists archive_other_apps;
do $$
declare t text;
begin
    foreach t in array array['medicines','stock','stock_invoices','stock_invoice_items','sales','sale_items','suppliers','payments','admin_users',
                             'exp_app_settings','exp_budgets','exp_categories','exp_currencies','exp_expenses']
    loop
        if to_regclass('public.' || t) is not null then
            execute format('alter table public.%I set schema archive_other_apps', t);
        end if;
    end loop;
end $$;
revoke all on schema archive_other_apps from public, anon, authenticated;

-- 2. remove EVERY old rule (live has permissive "Allow all ..." rules under other names than the staging ones)
do $$
declare r record;
begin
    for r in select schemaname, tablename, policyname from pg_policies where schemaname = 'public' loop
        execute format('drop policy %I on %I.%I', r.policyname, r.schemaname, r.tablename);
    end loop;
    for r in select policyname from pg_policies where schemaname = 'storage' and tablename = 'objects' loop
        execute format('drop policy %I on storage.objects', r.policyname);
    end loop;
end $$;

-- 3. one admin per company: supervisors are retired (kept, inactive, no login). Their old status is saved so the rollback can restore it.
create table if not exists archive_other_apps.supervisor_status_backup (id uuid primary key, status text, saved_at timestamptz default now());
insert into archive_other_apps.supervisor_status_backup (id, status) select id, status from public.users where role = 'supervisor' on conflict (id) do nothing;
update public.users set status = 'inactive' where role = 'supervisor';

-- >>>>>>>>>> live/000b_cleanup_live.sql
-- ============================================================
-- LIVE 000b: clean-up approved by the owner (ROADMAP S5). Part of live-cutover-bundle.sql, runs right after 000_prepare_live.sql.
-- THIS PART DELETES DATA and is NOT undone by the rollback bundle:
--   * companies AE2 (Hadir) and AE3 and everything that belongs to them
--   * punch locations of AE1 other than "Kaden Warehouse" and "Sulay" (a location that already has punches is kept, switched to inactive, so history stays)
--   * the retired AE1 supervisors (one that is still named in an approval or audit entry is kept, inactive)
--   * enrolment links that expired without ever being used
-- ============================================================
do $$
declare
    v_ids uuid[];
    t text;
    n int;
begin
    -- safety: only the tiny companies the owner named, and only if they are still that small
    select array_agg(id) into v_ids from public.clients where upper(client_code) in ('AE2', 'AE3');
    if v_ids is not null then
        select count(*) into n from public.laborers where client_id = any (v_ids);
        if n > 5 then raise exception 'AE2/AE3 now have % laborers (expected at most 1). Stopping - check before deleting.', n; end if;
        foreach t in array array['overtime_records', 'lop_requests', 'daily_attendance', 'punch_records', 'enrollment_links', 'laborers', 'iqama_registry', 'audit_log',
                                 'punch_locations', 'attendance_freeze', 'holidays', 'ot_rates', 'settings', 'users', 'departments'] loop
            if to_regclass('public.' || t) is not null and exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = t and column_name = 'client_id') then
                execute format('delete from public.%I where client_id = any ($1)', t) using v_ids;
            end if;
        end loop;
        delete from public.clients where id = any (v_ids);
    end if;
end $$;

-- AE1 punch locations: keep Kaden Warehouse and Sulay; drop the rest (or switch off when they already have punches)
delete from public.punch_locations l
 where l.client_id = (select id from public.clients where upper(client_code) = 'AE1')
   and l.name not in ('Kaden Warehouse', 'Sulay')
   and not exists (select 1 from public.punch_records p where p.location_id = l.id);
update public.punch_locations l set status = 'inactive'
 where l.client_id = (select id from public.clients where upper(client_code) = 'AE1')
   and l.name not in ('Kaden Warehouse', 'Sulay');

-- retired supervisors: delete those nobody refers to (the ones still named in approvals / audit stay inactive)
delete from public.users u
 where u.role = 'supervisor'
   and not exists (select 1 from public.lop_requests r where r.requested_by = u.id or r.approved_by = u.id)
   and not exists (select 1 from public.audit_log a where a.user_id = u.id);

-- enrolment links that expired and were never used
delete from public.enrollment_links where status = 'pending' and submitted_at is null and expires_at < now();

-- >>>>>>>>>> migrations/001_security_foundation.sql
-- ============================================================
-- Migration 001: security foundation (ROADMAP tasks 29-31, 43-45)
-- ============================================================
-- Replaces the temporary "allow all" access with real tenant isolation:
--   * a logged-in user (Supabase Auth) sees and changes ONLY the rows of their own client
--   * the public (anon) key can no longer read or write any table directly
--   * password hashes are no longer readable, clients cannot edit their own subscription
--
-- Run order on a project:  schema.sql  ->  (policies-temporary-open.sql, staging only)  ->  001 (this file)
-- DO NOT apply to a project whose app still uses the old login (app would stop working).
-- Tested on local Postgres 16 with stand-ins for Supabase's auth schema: tests/db/ (run: bash tests/db/run.sh).
-- NOT yet applied to any Supabase project.
-- ============================================================

-- 1. Link our users table to Supabase Auth users
alter table public.users add column if not exists auth_id uuid unique references auth.users(id) on delete cascade;

-- 2. Who is the caller? Resolved from the Auth session (auth.uid()), never from anything the browser sends.
create or replace function public.current_client_id()
returns uuid language sql stable security definer set search_path = public as $$
    select client_id from public.users where auth_id = auth.uid() and status = 'active' limit 1
$$;
create or replace function public.current_user_role()
returns text language sql stable security definer set search_path = public as $$
    select role from public.users where auth_id = auth.uid() and status = 'active' limit 1
$$;
revoke all on function public.current_client_id(), public.current_user_role() from public, anon;
grant execute on function public.current_client_id(), public.current_user_role() to authenticated;

-- 3. Close the public (anon) door completely; later steps give the punch terminal its own narrow functions
revoke all on all tables    in schema public from anon;
revoke all on all sequences in schema public from anon;
revoke all on all functions in schema public from anon;
alter default privileges in schema public revoke all on tables    from anon;
alter default privileges in schema public revoke all on functions from anon;

-- 4. Remove the temporary open policies (created by policies-temporary-open.sql, if present)
do $$
declare r record;
begin
    for r in select policyname, tablename from pg_policies where schemaname = 'public' and policyname like 'tmp allow all %' loop
        execute format('drop policy %I on public.%I', r.policyname, r.tablename);
    end loop;
end $$;

-- 5. Row level security ON for every attendance table (including the three that had it OFF)
do $$
declare t text;
begin
    foreach t in array array['clients','users','departments','laborers','punch_locations','punch_records','daily_attendance',
        'lop_requests','audit_log','settings','labor_id_sequence','attendance_freeze','holidays','ot_rates','overtime_records',
        'iqama_registry','enrollment_links']
    loop execute format('alter table public.%I enable row level security', t); end loop;
end $$;

-- 6. Tenant tables: full access, but ONLY to rows of the caller's own client
do $$
declare t text;
begin
    foreach t in array array['departments','laborers','punch_locations','punch_records','daily_attendance','lop_requests','settings',
        'attendance_freeze','holidays','ot_rates','overtime_records','iqama_registry','enrollment_links']
    loop
        execute format('drop policy if exists %I on public.%I', 'tenant ' || t, t);
        execute format('create policy %I on public.%I for all to authenticated
                        using (client_id = (select public.current_client_id()))
                        with check (client_id = (select public.current_client_id()))', 'tenant ' || t, t);
        execute format('grant select, insert, update, delete on public.%I to authenticated', t);
        -- a row created without an explicit client_id belongs to the caller's client (no more hard-coded default client)
        execute format('alter table public.%I alter column client_id set default public.current_client_id()', t);
    end loop;
end $$;

-- 7. audit_log: add and read your own client's entries, never change or delete them
drop policy if exists "tenant audit_log select" on public.audit_log;
drop policy if exists "tenant audit_log insert" on public.audit_log;
create policy "tenant audit_log select" on public.audit_log for select to authenticated using (client_id = (select public.current_client_id()));
create policy "tenant audit_log insert" on public.audit_log for insert to authenticated with check (client_id = (select public.current_client_id()));
grant select, insert on public.audit_log to authenticated;
alter table public.audit_log alter column client_id set default public.current_client_id();

-- 8. users: you can read your OWN row, never anyone else's, and never the password hash column
drop policy if exists "own user row" on public.users;
create policy "own user row" on public.users for select to authenticated using (auth_id = auth.uid());
revoke all on public.users from authenticated;
grant select (id, username, name, role, department_id, status, created_at, updated_at, client_id, permissions, auth_id) on public.users to authenticated;

-- 9. clients: read your own company row only; nobody can change subscription data from the app
drop policy if exists "own client row" on public.clients;
create policy "own client row" on public.clients for select to authenticated using (id = (select public.current_client_id()));
revoke all on public.clients from authenticated;
grant select on public.clients to authenticated;

-- 10. labor_id_sequence: only the functions below touch it (no direct access)
revoke all on public.labor_id_sequence from authenticated;

-- 11. functions: run with fixed search_path, check the caller's client, not callable by the public key
create or replace function public.get_next_labor_id()
returns text language plpgsql security definer set search_path = public as $$
declare next_id integer;
begin
    if public.current_client_id() is null then raise exception 'not allowed' using errcode = '42501'; end if;
    update labor_id_sequence set next_value = next_value + 1 where id = 1 returning next_value - 1 into next_id;
    return 'L' || next_id::text;
end;
$$;

create or replace function public.register_iqama(p_iqama text)
returns text language plpgsql security definer set search_path = public as $$
declare
    v_client uuid := public.current_client_id();
    existing_labor_id text;
    new_labor_id text;
begin
    if v_client is null then raise exception 'not allowed' using errcode = '42501'; end if;
    select labor_id into existing_labor_id from iqama_registry where iqama_number = p_iqama and client_id = v_client;
    if existing_labor_id is not null then return existing_labor_id; end if;
    new_labor_id := public.get_next_labor_id();
    insert into iqama_registry (iqama_number, labor_id, client_id) values (p_iqama, new_labor_id, v_client);
    return new_labor_id;
end;
$$;

-- same calculation as before; only the caller check and fixed search_path are new
create or replace function public.update_daily_attendance(p_labor_id text, p_date date)
returns void language plpgsql security definer set search_path = public as $$
declare
    v_caller uuid := public.current_client_id();
    v_client_id uuid;
    v_department_id uuid;
    v_first_login time;
    v_last_logout time;
    v_total_hours numeric;
    v_total_minutes integer;
    v_auto_status text;
    v_min_present_minutes integer := 570;
    v_min_half_minutes integer := 240;
    v_dept_min_hours text;
begin
    select client_id, department_id into v_client_id, v_department_id from laborers where labor_id = p_labor_id limit 1;
    if v_client_id is null then return; end if;
    if v_caller is null or v_caller <> v_client_id then raise exception 'not allowed' using errcode = '42501'; end if;

    select min(time), max(time) into v_first_login, v_last_logout
    from punch_records where labor_id = p_labor_id and date = p_date and client_id = v_client_id;
    if v_first_login is null then return; end if;

    select min_hours_full_day into v_dept_min_hours from departments where id = v_department_id limit 1;
    if v_dept_min_hours is not null then
        v_min_present_minutes := extract(hour from v_dept_min_hours::time) * 60 + extract(minute from v_dept_min_hours::time);
    end if;

    v_total_minutes := extract(epoch from (v_last_logout - v_first_login)) / 60;
    v_total_hours   := v_total_minutes / 60.0;
    if v_total_minutes >= v_min_present_minutes then v_auto_status := 'P';
    elsif v_total_minutes >= v_min_half_minutes then v_auto_status := 'H';
    else v_auto_status := 'A'; end if;

    insert into daily_attendance (labor_id, department_id, date, first_login, last_logout, total_hours, auto_status, final_status, client_id, updated_at)
    values (p_labor_id, v_department_id, p_date, v_first_login, v_last_logout, v_total_hours, v_auto_status, v_auto_status, v_client_id, now())
    on conflict (labor_id, date) do update set
        first_login = excluded.first_login, last_logout = excluded.last_logout, total_hours = excluded.total_hours,
        auto_status = excluded.auto_status,
        final_status = case when daily_attendance.final_status in ('LP','LH','LA') then daily_attendance.final_status else excluded.auto_status end,
        updated_at = now();
end;
$$;

revoke all on function public.get_next_labor_id(), public.register_iqama(text), public.update_daily_attendance(text, date) from public, anon;
grant execute on function public.get_next_labor_id(), public.register_iqama(text), public.update_daily_attendance(text, date) to authenticated;
-- the old helper that read settings without any client check is not used by the app: keep it away from the public key
revoke all on function public.calculate_attendance_status(numeric) from public, anon;

-- ============================================================
-- Changelog
-- 2026-10-02  001  Written and tested locally (tests/db). Not applied to any Supabase project yet.
-- ============================================================

-- >>>>>>>>>> migrations/002_auth_login.sql
-- ============================================================
-- Migration 002: login through Supabase Auth, one admin per client (ROADMAP S2; tasks 14, 26, 47)
-- ============================================================
-- Run AFTER 001. Tested on local Postgres (tests/db). NOT yet applied to any Supabase project.
--
-- How login works after this:
--   * the app signs in with Supabase Auth using the email  <username>@<company code>.dawam.arwaenterprises.com  and the password
--     (the person still types Company code + Username + Password; the email is built by the app, nothing is ever sent to it)
--   * an Auth account only gets access to data once it is LINKED to a company with  public.link_admin_profile(...)
--     (run by the platform owner in the SQL editor). Nobody can link themselves, so even if public sign-up were left on,
--     a stranger who registers an address would see nothing.
-- ============================================================

-- 1. passwords now live in Supabase Auth, not in our table
alter table public.users alter column password_hash drop not null;

-- 2. a username only has to be unique inside its company (two companies can both have "admin")
alter table public.users drop constraint if exists users_username_key;
alter table public.users add constraint users_client_username_key unique (client_id, username);

-- 3. exactly one ACTIVE admin per company (to replace an admin: set the old one inactive, then add the new one)
--    If this fails on an existing database, that company has several active admins: decide who stays, then re-run.
create unique index if not exists users_one_admin_per_client on public.users (client_id) where role = 'admin' and status = 'active';

-- 4. settings: unique per company + key (was: key alone, so two companies could not both have "night_shift_start")
alter table public.settings alter column client_id set not null;
alter table public.settings drop constraint if exists settings_pkey;
alter table public.settings add primary key (client_id, key);

-- 5. a company that is deactivated or whose subscription ended gets no data access at all (enforced here, not only in the app)
create or replace function public.current_client_id()
returns uuid language sql stable security definer set search_path = public as $$
    select u.client_id
    from public.users u join public.clients c on c.id = u.client_id
    where u.auth_id = auth.uid()
      and u.status = 'active'
      and c.is_active
      and c.subscription_status is distinct from 'expired'
      and (c.subscription_status = 'premium' or c.subscription_end_date is null or c.subscription_end_date >= current_date)
    limit 1
$$;
create or replace function public.current_user_role()
returns text language sql stable security definer set search_path = public as $$
    select u.role
    from public.users u join public.clients c on c.id = u.client_id
    where u.auth_id = auth.uid() and u.status = 'active' and c.is_active
      and c.subscription_status is distinct from 'expired'
      and (c.subscription_status = 'premium' or c.subscription_end_date is null or c.subscription_end_date >= current_date)
    limit 1
$$;

-- 6. platform-owner command: link an Auth account to a company (creates the admin profile, or links an existing one)
--    Usage (SQL editor):  select public.link_admin_profile('TEST', 'admin', 'Test Admin');
--    The Auth account (Authentication > Users > Add user) must exist first, with email  admin@test.dawam.arwaenterprises.com
create or replace function public.link_admin_profile(p_client_code text, p_username text, p_name text default null)
returns text language plpgsql security definer set search_path = public, auth as $$
declare
    v_client uuid;
    v_email  text;
    v_auth   uuid;
    v_user   text := lower(btrim(p_username));
begin
    select id into v_client from public.clients where upper(client_code) = upper(btrim(p_client_code));
    if v_client is null then raise exception 'unknown company code: %', p_client_code; end if;
    v_email := v_user || '@' || lower(btrim(p_client_code)) || '.dawam.arwaenterprises.com';
    select id into v_auth from auth.users where lower(email) = v_email;
    if v_auth is null then raise exception 'create the Auth account first (Authentication > Users > Add user) with email: %', v_email; end if;

    update public.users set auth_id = v_auth, status = 'active' where client_id = v_client and username = v_user;
    if not found then
        insert into public.users (username, name, role, status, client_id, auth_id)
        values (v_user, coalesce(p_name, p_username), 'admin', 'active', v_client, v_auth);
    end if;
    return v_email;
end;
$$;
revoke all on function public.link_admin_profile(text, text, text) from public, anon, authenticated;

-- ============================================================
-- Changelog
-- 2026-10-02  002  Written and tested locally. Not applied to any Supabase project yet.
-- ============================================================

-- >>>>>>>>>> migrations/003_lop_labor_fk.sql
-- ============================================================
-- Migration 003: link LOP requests to laborers (ROADMAP finding 58)
-- ============================================================
-- Bug on the LIVE site today: the LOP lists (attendance/lop.html: pending / approved / rejected / draft) ask the database for
-- "laborers:labor_id(...)" but there is no foreign key lop_requests.labor_id -> laborers.labor_id, so the database answers
-- 400 "Could not find a relationship" and the lists cannot load. Verified against live with a read-only request that returns no rows.
-- Safe on a database with old data: the key is added NOT VALID (checks only new rows), then we try to validate the old rows.
-- ============================================================
do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'lop_requests_labor_id_fkey') then
        alter table public.lop_requests
            add constraint lop_requests_labor_id_fkey foreign key (labor_id) references public.laborers (labor_id) not valid;
    end if;
end $$;

do $$
begin
    alter table public.lop_requests validate constraint lop_requests_labor_id_fkey;
exception when foreign_key_violation then
    raise notice 'Some OLD LOP requests point to labor IDs that do not exist. The key stays NOT VALID (new rows are still checked). Find them with: select labor_id from lop_requests where labor_id not in (select labor_id from laborers);';
end $$;

-- >>>>>>>>>> migrations/004_terminal.sql
-- ============================================================
-- Migration 004: the punch terminal gets its own identity and ONLY narrow functions (ROADMAP S3; finding 59)
-- ============================================================
-- Run AFTER 001-003. Tested on local Postgres (tests/db). NOT yet applied to any Supabase project.
--
-- The terminal (tablet at the gate) signs in like a user, but as the role "terminal" of one company:
--     email  terminal@<company code>.dawam.arwaenterprises.com   password = the TERMINAL KEY
-- A terminal can NOT read or change any table directly. It can only call the terminal_* functions below, which return
-- exactly what a terminal needs (never salaries, ID numbers or other staff data).
-- Admins/supervisors keep their access; their table rules now also check the role.
-- ============================================================

-- 1. a new role value
alter table public.users drop constraint if exists users_role_check;
alter table public.users add constraint users_role_check check (role = any (array['super_admin', 'admin', 'supervisor', 'terminal']));

-- 2. role helpers
create or replace function public.is_staff()
returns boolean language sql stable security definer set search_path = public as $$
    select coalesce(public.current_user_role() in ('admin', 'supervisor', 'super_admin'), false)
$$;
create or replace function public.require_terminal()
returns uuid language plpgsql stable security definer set search_path = public as $$
declare v uuid := public.current_client_id();
begin
    if v is null or public.current_user_role() is distinct from 'terminal' then
        raise exception 'not allowed' using errcode = '42501';
    end if;
    return v;
end;
$$;
revoke all on function public.is_staff(), public.require_terminal() from public, anon;
grant execute on function public.is_staff(), public.require_terminal() to authenticated;

-- 3. table rules: only staff (admin / supervisor), never the terminal
do $$
declare t text;
begin
    foreach t in array array['departments','laborers','punch_locations','punch_records','daily_attendance','lop_requests','settings',
        'attendance_freeze','holidays','ot_rates','overtime_records','iqama_registry','enrollment_links']
    loop
        execute format('drop policy if exists %I on public.%I', 'tenant ' || t, t);
        execute format('create policy %I on public.%I for all to authenticated
                        using (client_id = (select public.current_client_id()) and (select public.is_staff()))
                        with check (client_id = (select public.current_client_id()) and (select public.is_staff()))', 'tenant ' || t, t);
    end loop;
end $$;
drop policy if exists "tenant audit_log select" on public.audit_log;
drop policy if exists "tenant audit_log insert" on public.audit_log;
create policy "tenant audit_log select" on public.audit_log for select to authenticated using (client_id = (select public.current_client_id()) and (select public.is_staff()));
create policy "tenant audit_log insert" on public.audit_log for insert to authenticated with check (client_id = (select public.current_client_id()) and (select public.is_staff()));

-- 4. attendance recalculation: an internal worker + the public wrapper (same maths as before)
create or replace function public._recalc_attendance(p_client uuid, p_labor_id text, p_date date)
returns void language plpgsql security definer set search_path = public as $$
declare
    v_department_id uuid;
    v_first_login time;
    v_last_logout time;
    v_total_hours numeric;
    v_total_minutes integer;
    v_auto_status text;
    v_min_present_minutes integer := 570;
    v_min_half_minutes integer := 240;
    v_dept_min_hours text;
begin
    select department_id into v_department_id from laborers where labor_id = p_labor_id and client_id = p_client limit 1;
    if v_department_id is null then return; end if;

    select min(time), max(time) into v_first_login, v_last_logout
    from punch_records where labor_id = p_labor_id and date = p_date and client_id = p_client;
    if v_first_login is null then return; end if;

    select min_hours_full_day into v_dept_min_hours from departments where id = v_department_id limit 1;
    if v_dept_min_hours is not null then
        v_min_present_minutes := extract(hour from v_dept_min_hours::time) * 60 + extract(minute from v_dept_min_hours::time);
    end if;

    v_total_minutes := extract(epoch from (v_last_logout - v_first_login)) / 60;
    v_total_hours   := v_total_minutes / 60.0;
    if v_total_minutes >= v_min_present_minutes then v_auto_status := 'P';
    elsif v_total_minutes >= v_min_half_minutes then v_auto_status := 'H';
    else v_auto_status := 'A'; end if;

    insert into daily_attendance (labor_id, department_id, date, first_login, last_logout, total_hours, auto_status, final_status, client_id, updated_at)
    values (p_labor_id, v_department_id, p_date, v_first_login, v_last_logout, v_total_hours, v_auto_status, v_auto_status, p_client, now())
    on conflict (labor_id, date) do update set
        first_login = excluded.first_login, last_logout = excluded.last_logout, total_hours = excluded.total_hours,
        auto_status = excluded.auto_status,
        final_status = case when daily_attendance.final_status in ('LP','LH','LA') then daily_attendance.final_status else excluded.auto_status end,
        updated_at = now();
end;
$$;
revoke all on function public._recalc_attendance(uuid, text, date) from public, anon, authenticated;

create or replace function public.update_daily_attendance(p_labor_id text, p_date date)
returns void language plpgsql security definer set search_path = public as $$
declare
    v_caller uuid := public.current_client_id();
    v_client uuid;
begin
    select client_id into v_client from laborers where labor_id = p_labor_id limit 1;
    if v_client is null then return; end if;
    if v_caller is null or v_caller <> v_client or public.current_user_role() not in ('admin', 'supervisor', 'super_admin', 'terminal') then
        raise exception 'not allowed' using errcode = '42501';
    end if;
    perform public._recalc_attendance(v_client, p_labor_id, p_date);
end;
$$;
-- staff only (a terminal must not consume labor ids or register ID numbers)
create or replace function public.get_next_labor_id()
returns text language plpgsql security definer set search_path = public as $$
declare next_id integer;
begin
    if public.current_client_id() is null or not public.is_staff() then raise exception 'not allowed' using errcode = '42501'; end if;
    update labor_id_sequence set next_value = next_value + 1 where id = 1 returning next_value - 1 into next_id;
    return 'L' || next_id::text;
end;
$$;
create or replace function public.register_iqama(p_iqama text)
returns text language plpgsql security definer set search_path = public as $$
declare
    v_client uuid := public.current_client_id();
    existing_labor_id text;
    new_labor_id text;
begin
    if v_client is null or not public.is_staff() then raise exception 'not allowed' using errcode = '42501'; end if;
    select labor_id into existing_labor_id from iqama_registry where iqama_number = p_iqama and client_id = v_client;
    if existing_labor_id is not null then return existing_labor_id; end if;
    new_labor_id := public.get_next_labor_id();
    insert into iqama_registry (iqama_number, labor_id, client_id) values (p_iqama, new_labor_id, v_client);
    return new_labor_id;
end;
$$;

-- 5. THE TERMINAL FUNCTIONS
-- 5a. everything the terminal keeps for offline use, in one call (no salaries, no ID numbers)
create or replace function public.terminal_bootstrap()
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare v uuid := public.require_terminal();
begin
    return jsonb_build_object(
        'client', (select jsonb_build_object('id', c.id, 'client_code', c.client_code, 'business_name', c.business_name, 'subscribed_apps', c.subscribed_apps)
                   from clients c where c.id = v),
        'settings', (select coalesce(jsonb_object_agg(s.key, s.value), '{}'::jsonb) from settings s where s.client_id = v),
        'locations', (select coalesce(jsonb_agg(to_jsonb(l) order by l.name), '[]'::jsonb) from punch_locations l where l.client_id = v and l.status = 'active'),
        'laborers', (select coalesce(jsonb_agg(jsonb_build_object('labor_id', b.labor_id, 'name', b.name, 'department_id', b.department_id,
                        'face_descriptor', b.face_descriptor, 'face_enrolled', b.face_enrolled) order by b.labor_id), '[]'::jsonb)
                     from laborers b where b.client_id = v and b.status = 'active' and b.face_enrolled)
    );
end;
$$;

-- 5b. punches of one labor on one day (for the "my punches" screen)
create or replace function public.terminal_today_punches(p_labor_id text, p_date date)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare v uuid := public.require_terminal();
begin
    return coalesce((select jsonb_agg(jsonb_build_object('id', r.id, 'type', r.type, 'time', r.time, 'date', r.date,
                    'location_name', r.location_name, 'photo_url', r.photo_url, 'created_at', r.created_at) order by r.created_at)
                    from punch_records r where r.client_id = v and r.labor_id = p_labor_id and r.date = p_date), '[]'::jsonb);
end;
$$;

-- 5c. how many punches today, the daily limit, and the last punch type (decides the next type and the limit)
create or replace function public.terminal_punch_state(p_labor_id text, p_date date)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare v uuid := public.require_terminal();
begin
    return jsonb_build_object(
        'count', (select count(*) from punch_records where client_id = v and labor_id = p_labor_id and date = p_date),
        'max', coalesce((select nullif(value, '')::int from settings where client_id = v and key = 'max_punches_per_day'), 999),
        'last_type', (select type from punch_records where client_id = v and labor_id = p_labor_id and date = p_date order by time desc limit 1)
    );
end;
$$;

-- 5d. record one punch (online, or an offline punch being uploaded). Same rules the app had, now decided by the database:
--     night-shift date correction (settings night_shift_start/end), duplicates ignored, attendance recalculated.
create or replace function public.terminal_record_punch(p jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
    v_client uuid := public.require_terminal();
    v_labor_id text := p ->> 'labor_id';
    v_labor record;
    v_date date;
    v_time time;
    v_type text := p ->> 'type';
    v_night_start int := 20 * 60;
    v_night_end int := 6 * 60 + 30;
    v_val text;
    v_mins int;
    v_prev date;
    v_final_date date;
    v_is_night_end boolean := false;
    v_location uuid := null;
    v_conf int := null;
    v_photo text := nullif(p ->> 'photo_url', '');
    v_id uuid;
    v_existing uuid;
begin
    select * into v_labor from laborers where client_id = v_client and labor_id = v_labor_id and status = 'active';
    if not found then raise exception 'unknown or inactive labor' using errcode = 'P0001'; end if;
    if v_type is null or v_type not in ('login', 'logout') then raise exception 'invalid punch type' using errcode = 'P0001'; end if;
    begin
        v_date := (p ->> 'date')::date;
        v_time := (p ->> 'time')::time;
    exception when others then raise exception 'invalid date or time' using errcode = 'P0001'; end;
    if v_date is null or v_time is null or v_date < current_date - 31 or v_date > current_date + 1 then
        raise exception 'date out of range' using errcode = 'P0001';
    end if;
    if p ->> 'location_id' is not null then
        select id into v_location from punch_locations where id = (p ->> 'location_id')::uuid and client_id = v_client;
    end if;
    if p ->> 'confidence' is not null then v_conf := greatest(0, least(100, (p ->> 'confidence')::int)); end if;
    if v_photo is not null and length(v_photo) > 500 then raise exception 'photo link too long' using errcode = 'P0001'; end if;

    select value into v_val from settings where client_id = v_client and key = 'night_shift_start';
    if v_val ~ '^\d{1,2}:\d{2}' then v_night_start := split_part(v_val, ':', 1)::int * 60 + split_part(v_val, ':', 2)::int; end if;
    select value into v_val from settings where client_id = v_client and key = 'night_shift_end';
    if v_val ~ '^\d{1,2}:\d{2}' then v_night_end := split_part(v_val, ':', 1)::int * 60 + split_part(v_val, ':', 2)::int; end if;

    v_final_date := v_date;
    v_mins := extract(hour from v_time)::int * 60 + extract(minute from v_time)::int;
    if v_mins <= v_night_end then
        v_prev := v_date - 1;
        if exists (select 1 from punch_records where client_id = v_client and labor_id = v_labor_id and date = v_prev
                   and extract(hour from time)::int * 60 + extract(minute from time)::int >= v_night_start) then
            v_final_date := v_prev; v_is_night_end := true;
        end if;
    end if;

    select id into v_existing from punch_records where client_id = v_client and labor_id = v_labor_id and date = v_final_date and time = v_time limit 1;
    if v_existing is not null then
        return jsonb_build_object('success', true, 'duplicate', true, 'id', v_existing, 'date', v_final_date);
    end if;

    insert into punch_records (labor_id, department_id, date, time, type, location_id, location_name, confidence, photo_url, client_id, is_night_shift_end)
    values (v_labor_id, v_labor.department_id, v_final_date, v_time, v_type, v_location, left(p ->> 'location_name', 200), v_conf, v_photo, v_client, v_is_night_end)
    returning id into v_id;

    update laborers set last_sync_at = now() where id = v_labor.id;
    perform public._recalc_attendance(v_client, v_labor_id, v_final_date);
    return jsonb_build_object('success', true, 'duplicate', false, 'id', v_id, 'date', v_final_date, 'is_night_shift_end', v_is_night_end);
end;
$$;

-- 5e. a face that matched badly: count it, flag for re-enrollment after 3 in a week (same rule as before)
create or replace function public.terminal_low_confidence(p_labor_id text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
    v uuid := public.require_terminal();
    v_labor record;
    v_new int;
    v_needs boolean;
begin
    select * into v_labor from laborers where client_id = v and labor_id = p_labor_id and status = 'active';
    if not found then raise exception 'unknown or inactive labor' using errcode = 'P0001'; end if;
    v_new := coalesce(v_labor.low_confidence_count, 0) + 1;
    if v_labor.last_low_confidence_date is not null and (current_date - v_labor.last_low_confidence_date) > 7 then v_new := 1; end if;
    v_needs := v_new >= 3;
    update laborers set low_confidence_count = v_new, last_low_confidence_date = current_date, needs_reenrollment = v_needs where id = v_labor.id;
    return jsonb_build_object('success', true, 'needs_reenrollment', v_needs);
end;
$$;

revoke all on function public.update_daily_attendance(text, date), public.get_next_labor_id(), public.register_iqama(text),
    public.terminal_bootstrap(), public.terminal_today_punches(text, date), public.terminal_punch_state(text, date),
    public.terminal_record_punch(jsonb), public.terminal_low_confidence(text) from public, anon;
grant execute on function public.update_daily_attendance(text, date), public.get_next_labor_id(), public.register_iqama(text),
    public.terminal_bootstrap(), public.terminal_today_punches(text, date), public.terminal_punch_state(text, date),
    public.terminal_record_punch(jsonb), public.terminal_low_confidence(text) to authenticated;

-- 6. platform-owner command: link a company's terminal login (Authentication > Users > Add user, email below, password = the terminal key)
--    Usage (SQL editor):  select public.link_terminal_profile('TEST');
create or replace function public.link_terminal_profile(p_client_code text, p_name text default 'Punch Terminal')
returns text language plpgsql security definer set search_path = public, auth as $$
declare
    v_client uuid;
    v_email  text;
    v_auth   uuid;
begin
    select id into v_client from public.clients where upper(client_code) = upper(btrim(p_client_code));
    if v_client is null then raise exception 'unknown company code: %', p_client_code; end if;
    v_email := 'terminal@' || lower(btrim(p_client_code)) || '.dawam.arwaenterprises.com';
    select id into v_auth from auth.users where lower(email) = v_email;
    if v_auth is null then raise exception 'create the Auth account first (Authentication > Users > Add user) with email: %', v_email; end if;
    update public.users set auth_id = v_auth, status = 'active', role = 'terminal' where client_id = v_client and username = 'terminal';
    if not found then
        insert into public.users (username, name, role, status, client_id, auth_id) values ('terminal', p_name, 'terminal', 'active', v_client, v_auth);
    end if;
    return v_email;
end;
$$;
revoke all on function public.link_terminal_profile(text, text) from public, anon, authenticated;

-- 7. photos: the old open storage rules (staging only) go; a terminal may ADD photos, nobody else can through the public key.
--    (Photos are still in a public bucket; step S4 makes them private and company-separated.)
drop policy if exists "tmp punch-photos select" on storage.objects;
drop policy if exists "tmp punch-photos insert" on storage.objects;
drop policy if exists "tmp punch-photos delete" on storage.objects;
drop policy if exists "terminal adds punch photos" on storage.objects;
create policy "terminal adds punch photos" on storage.objects for insert to authenticated
    with check (bucket_id = 'punch-photos' and public.current_user_role() = 'terminal');

-- ============================================================
-- Changelog
-- 2026-10-02  004  Written and tested locally. Not applied to any Supabase project yet.
-- ============================================================

-- >>>>>>>>>> migrations/005_terminal_least_privilege.sql
-- ============================================================
-- Migration 005: a terminal cannot read the company row (ROADMAP S3 hardening)
-- ============================================================
-- Found by the end-to-end terminal test on staging: the rule "you may read your own company row" (migration 001) also let a
-- terminal read its company's contact and subscription details. A terminal does not need them (it gets the company name and code
-- through terminal_bootstrap), so only staff (admin / supervisor) may read the company row now.
drop policy if exists "own client row" on public.clients;
create policy "own client row" on public.clients for select to authenticated
    using (id = (select public.current_client_id()) and (select public.is_staff()));

-- >>>>>>>>>> migrations/006_private_photos.sql
-- ============================================================
-- Migration 006: private punch photos + safe self-enrollment (ROADMAP S4; findings 33, 45)
-- ============================================================
-- Run AFTER 001-005. Tested on local Postgres (tests/db); the storage rules are also tested on the real staging project (tests/photos.test.js).
-- NOT yet applied to any Supabase project.
--
-- Before: the photo bucket was PUBLIC: anyone with a photo link could open it; (staging) anyone with the public key could upload or delete.
-- After:
--   * the bucket is private (+ 5 MB, JPEG only); photos are shown through short-lived signed links
--   * photo files live in a folder per company:   <company id>/punches/...   and   <company id>/enrollment/...
--   * staff (admin/supervisor) and the company's terminal can read their OWN company's photos; staff can delete them
--   * a terminal can add photos only to its own company's  punches  folder
--   * a labor with a valid, unused, unexpired enrollment link can add exactly ONE photo: <company id>/enrollment/<token>.jpg
--   * the self-enrollment page no longer reads or writes tables: it uses enrollment_get / enrollment_submit
-- Photos taken before this change (old paths without a company folder) stay readable by the company that owns them, found through the
-- punch / enrollment record that points at the file. The 15-day photo cleanup removes them; then this lookup is no longer needed.
-- ============================================================

-- 1. who owns a photo file?
create or replace function public.photo_client(p_name text)
returns uuid language plpgsql stable security definer set search_path = public as $$
declare
    v_first text := (storage.foldername(p_name))[1];
    v uuid;
begin
    if v_first ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' then
        return v_first::uuid;
    end if;
    -- old path without a company folder: owned by the company whose record points at the file
    select client_id into v from punch_records where photo_url is not null and right(photo_url, length(p_name)) = p_name limit 1;
    if v is null then
        select client_id into v from enrollment_links where photo_url is not null and right(photo_url, length(p_name)) = p_name limit 1;
    end if;
    return v;
end;
$$;

-- 2. may this exact file be uploaded by someone holding an enrollment link?  path = <company id>/enrollment/<token>.jpg
create or replace function public.enrollment_upload_allowed(p_name text)
returns boolean language plpgsql stable security definer set search_path = public as $$
declare
    f text[] := storage.foldername(p_name);
    v_token text;
begin
    if array_length(f, 1) is distinct from 2 or f[2] <> 'enrollment' then return false; end if;
    if right(p_name, 4) <> '.jpg' then return false; end if;
    v_token := substr(storage.filename(p_name), 1, length(storage.filename(p_name)) - 4);
    return exists (select 1 from enrollment_links l
                   where l.token = v_token and l.client_id::text = f[1] and l.status = 'pending' and l.expires_at > now());
end;
$$;
revoke all on function public.photo_client(text), public.enrollment_upload_allowed(text) from public;
grant execute on function public.photo_client(text) to authenticated;
grant execute on function public.enrollment_upload_allowed(text) to anon, authenticated;

-- 3. the bucket: private, JPEG only, 5 MB
update storage.buckets set public = false, file_size_limit = 5242880, allowed_mime_types = array['image/jpeg'] where id = 'punch-photos';

-- 4. storage rules
drop policy if exists "terminal adds punch photos" on storage.objects;
drop policy if exists "tmp punch-photos select" on storage.objects;
drop policy if exists "tmp punch-photos insert" on storage.objects;
drop policy if exists "tmp punch-photos delete" on storage.objects;
drop policy if exists "own company reads photos" on storage.objects;
drop policy if exists "staff delete own company photos" on storage.objects;
drop policy if exists "terminal adds own company photos" on storage.objects;
drop policy if exists "enrollment link adds its photo" on storage.objects;
drop policy if exists "enrollment link retakes its photo" on storage.objects;

create policy "own company reads photos" on storage.objects for select to authenticated
    using (bucket_id = 'punch-photos'
           and public.current_user_role() in ('admin', 'supervisor', 'super_admin', 'terminal')
           and public.photo_client(name) = public.current_client_id());
create policy "staff delete own company photos" on storage.objects for delete to authenticated
    using (bucket_id = 'punch-photos' and public.is_staff() and public.photo_client(name) = public.current_client_id());
create policy "terminal adds own company photos" on storage.objects for insert to authenticated
    with check (bucket_id = 'punch-photos' and public.current_user_role() = 'terminal'
                and (storage.foldername(name))[1] = public.current_client_id()::text and (storage.foldername(name))[2] = 'punches');
create policy "enrollment link adds its photo" on storage.objects for insert to anon
    with check (bucket_id = 'punch-photos' and public.enrollment_upload_allowed(name));
create policy "enrollment link retakes its photo" on storage.objects for update to anon
    using (bucket_id = 'punch-photos' and public.enrollment_upload_allowed(name))
    with check (bucket_id = 'punch-photos' and public.enrollment_upload_allowed(name));

-- 5. self-enrollment without table access
create or replace function public.enrollment_get(p_token text)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare l record;
begin
    select * into l from enrollment_links where token = p_token;
    if not found then return jsonb_build_object('ok', false, 'reason', 'invalid'); end if;
    if l.status <> 'pending' then return jsonb_build_object('ok', false, 'reason', l.status); end if;     -- submitted / approved / expired / rejected
    if l.expires_at < now() then return jsonb_build_object('ok', false, 'reason', 'expired'); end if;
    return jsonb_build_object('ok', true, 'id', l.id, 'labor_id', l.labor_id, 'client_id', l.client_id, 'expires_at', l.expires_at,
        'labor_name', coalesce(l.labor_name, (select name from laborers where labor_id = l.labor_id and client_id = l.client_id), l.labor_id));
end;
$$;

create or replace function public.enrollment_submit(p_token text, p_descriptor text, p_photo_path text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
    l record;
    d jsonb;
begin
    select * into l from enrollment_links where token = p_token for update;
    if not found then raise exception 'Invalid link' using errcode = 'P0001'; end if;
    if l.status <> 'pending' then raise exception 'Link has already been used' using errcode = 'P0001'; end if;
    if l.expires_at < now() then raise exception 'Link has expired' using errcode = 'P0001'; end if;
    if p_photo_path is distinct from (l.client_id::text || '/enrollment/' || p_token || '.jpg') then raise exception 'Invalid photo' using errcode = 'P0001'; end if;
    if not exists (select 1 from storage.objects where bucket_id = 'punch-photos' and name = p_photo_path) then raise exception 'Photo was not uploaded' using errcode = 'P0001'; end if;
    begin d := p_descriptor::jsonb; exception when others then raise exception 'Invalid face data' using errcode = 'P0001'; end;
    if jsonb_typeof(d) <> 'array' or jsonb_array_length(d) not between 64 and 512 or length(p_descriptor) > 20000 then raise exception 'Invalid face data' using errcode = 'P0001'; end if;
    update enrollment_links set photo_url = p_photo_path, face_descriptor = p_descriptor, status = 'submitted', submitted_at = now() where id = l.id;
    return jsonb_build_object('success', true);
end;
$$;
revoke all on function public.enrollment_get(text), public.enrollment_submit(text, text, text) from public;
grant execute on function public.enrollment_get(text), public.enrollment_submit(text, text, text) to anon, authenticated;

-- 6. a terminal may only point a punch at a photo inside its own company folder (or keep an old-style link)
create or replace function public.terminal_record_punch(p jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
    v_client uuid := public.require_terminal();
    v_labor_id text := p ->> 'labor_id';
    v_labor record;
    v_date date;
    v_time time;
    v_type text := p ->> 'type';
    v_night_start int := 20 * 60;
    v_night_end int := 6 * 60 + 30;
    v_val text;
    v_mins int;
    v_prev date;
    v_final_date date;
    v_is_night_end boolean := false;
    v_location uuid := null;
    v_conf int := null;
    v_photo text := nullif(p ->> 'photo_url', '');
    v_id uuid;
    v_existing uuid;
begin
    select * into v_labor from laborers where client_id = v_client and labor_id = v_labor_id and status = 'active';
    if not found then raise exception 'unknown or inactive labor' using errcode = 'P0001'; end if;
    if v_type is null or v_type not in ('login', 'logout') then raise exception 'invalid punch type' using errcode = 'P0001'; end if;
    begin
        v_date := (p ->> 'date')::date;
        v_time := (p ->> 'time')::time;
    exception when others then raise exception 'invalid date or time' using errcode = 'P0001'; end;
    if v_date is null or v_time is null or v_date < current_date - 31 or v_date > current_date + 1 then
        raise exception 'date out of range' using errcode = 'P0001';
    end if;
    if p ->> 'location_id' is not null then
        select id into v_location from punch_locations where id = (p ->> 'location_id')::uuid and client_id = v_client;
    end if;
    if p ->> 'confidence' is not null then v_conf := greatest(0, least(100, (p ->> 'confidence')::int)); end if;
    if v_photo is not null then
        if length(v_photo) > 500 then raise exception 'photo link too long' using errcode = 'P0001'; end if;
        -- a photo path must be inside this company's punches folder (a full web address from an old terminal is kept as it is)
        if v_photo !~ '^https?://' and (storage.foldername(v_photo))[1] is distinct from v_client::text then
            raise exception 'invalid photo path' using errcode = 'P0001';
        end if;
    end if;

    select value into v_val from settings where client_id = v_client and key = 'night_shift_start';
    if v_val ~ '^\d{1,2}:\d{2}' then v_night_start := split_part(v_val, ':', 1)::int * 60 + split_part(v_val, ':', 2)::int; end if;
    select value into v_val from settings where client_id = v_client and key = 'night_shift_end';
    if v_val ~ '^\d{1,2}:\d{2}' then v_night_end := split_part(v_val, ':', 1)::int * 60 + split_part(v_val, ':', 2)::int; end if;

    v_final_date := v_date;
    v_mins := extract(hour from v_time)::int * 60 + extract(minute from v_time)::int;
    if v_mins <= v_night_end then
        v_prev := v_date - 1;
        if exists (select 1 from punch_records where client_id = v_client and labor_id = v_labor_id and date = v_prev
                   and extract(hour from time)::int * 60 + extract(minute from time)::int >= v_night_start) then
            v_final_date := v_prev; v_is_night_end := true;
        end if;
    end if;

    select id into v_existing from punch_records where client_id = v_client and labor_id = v_labor_id and date = v_final_date and time = v_time limit 1;
    if v_existing is not null then
        return jsonb_build_object('success', true, 'duplicate', true, 'id', v_existing, 'date', v_final_date);
    end if;

    insert into punch_records (labor_id, department_id, date, time, type, location_id, location_name, confidence, photo_url, client_id, is_night_shift_end)
    values (v_labor_id, v_labor.department_id, v_final_date, v_time, v_type, v_location, left(p ->> 'location_name', 200), v_conf, v_photo, v_client, v_is_night_end)
    returning id into v_id;

    update laborers set last_sync_at = now() where id = v_labor.id;
    perform public._recalc_attendance(v_client, v_labor_id, v_final_date);
    return jsonb_build_object('success', true, 'duplicate', false, 'id', v_id, 'date', v_final_date, 'is_night_shift_end', v_is_night_end);
end;
$$;
revoke all on function public.terminal_record_punch(jsonb) from public, anon;
grant execute on function public.terminal_record_punch(jsonb) to authenticated;

-- ============================================================
-- Changelog
-- 2026-10-02  006  Written and tested locally. Not applied to any Supabase project yet.
-- ============================================================
