-- ============================================================
-- LIVE ROLLBACK BUNDLE (generated by tools/build-live-bundle.js - do not edit by hand)
-- Puts the OLD behaviour back so the previous app version (old login, public key access, public photos) works again.
-- Use only if the cutover has to be undone. Nothing is deleted: tables moved to archive_other_apps are moved back, supervisors get their old status.
-- After running it: revert the app switch (bump the version) so the site uses the old login again.
-- ============================================================

-- 1. new rules out
do $$
declare r record;
begin
    for r in select schemaname, tablename, policyname from pg_policies where schemaname = 'public' loop
        execute format('drop policy %I on %I.%I', r.policyname, r.schemaname, r.tablename);
    end loop;
    for r in select policyname from pg_policies where schemaname = 'storage' and tablename = 'objects' loop
        execute format('drop policy %I on storage.objects', r.policyname);
    end loop;
end $$;

-- 2. the old open access (as it was before the cutover): rules "allow all" on the tables that had security on, no security on users / clients / labor_id_sequence
do $$
declare t text;
begin
    foreach t in array array['departments','settings','punch_locations','laborers','punch_records','daily_attendance','iqama_registry','lop_requests',
                             'audit_log','enrollment_links','attendance_freeze','holidays','ot_rates','overtime_records'] loop
        execute format('alter table public.%I enable row level security', t);
        execute format('create policy %I on public.%I for all to anon, authenticated using (true) with check (true)', 'Allow all on ' || t, t);
    end loop;
    foreach t in array array['users','clients','labor_id_sequence'] loop
        execute format('alter table public.%I disable row level security', t);
    end loop;
    grant usage on schema public to anon, authenticated;
    grant all on all tables in schema public to anon, authenticated;
    grant all on all sequences in schema public to anon, authenticated;
    grant execute on all functions in schema public to anon, authenticated;
end $$;
alter table public.users alter column password_hash set not null;

-- 3. the old database functions (original bodies)
-- ---------- functions ----------
create or replace function public.get_next_labor_id()
returns text language plpgsql as $$
declare
    next_id integer;
begin
    update labor_id_sequence
    set next_value = next_value + 1
    where id = 1
    returning next_value - 1 into next_id;

    return 'L' || next_id::text;
end;
$$;

create or replace function public.register_iqama(p_iqama text)
returns text language plpgsql as $$
declare
    existing_labor_id text;
    new_labor_id text;
begin
    select labor_id into existing_labor_id from iqama_registry where iqama_number = p_iqama;
    if existing_labor_id is not null then
        return existing_labor_id;
    end if;

    new_labor_id := get_next_labor_id();
    insert into iqama_registry (iqama_number, labor_id) values (p_iqama, new_labor_id);
    return new_labor_id;
end;
$$;

create or replace function public.calculate_attendance_status(hours numeric)
returns text language plpgsql as $$
declare
    min_present decimal;
    min_half decimal;
begin
    select value::decimal into min_present from settings where key = 'min_hours_present';
    select value::decimal into min_half from settings where key = 'min_hours_half_day';

    if hours >= min_present then
        return 'P';
    elsif hours >= min_half then
        return 'H';
    else
        return 'A';
    end if;
end;
$$;

create or replace function public.update_daily_attendance(p_labor_id text, p_date date)
returns void language plpgsql security definer as $$
declare
    v_client_id uuid;
    v_department_id uuid;
    v_first_login time;
    v_last_logout time;
    v_total_hours numeric;
    v_total_minutes integer;
    v_auto_status text;
    v_min_present_minutes integer := 570;
    v_min_half_minutes integer := 240;
    v_dept_min_hours text;
begin
    select client_id, department_id
    into v_client_id, v_department_id
    from laborers
    where labor_id = p_labor_id
    limit 1;

    if v_client_id is null then return; end if;

    select min(time), max(time)
    into v_first_login, v_last_logout
    from punch_records
    where labor_id = p_labor_id
      and date = p_date
      and client_id = v_client_id;

    if v_first_login is null then return; end if;

    select min_hours_full_day
    into v_dept_min_hours
    from departments
    where id = v_department_id
    limit 1;

    if v_dept_min_hours is not null then
        v_min_present_minutes :=
            extract(hour from v_dept_min_hours::time) * 60 +
            extract(minute from v_dept_min_hours::time);
    end if;

    v_total_minutes := extract(epoch from (v_last_logout - v_first_login)) / 60;
    v_total_hours   := v_total_minutes / 60.0;

    if v_total_minutes >= v_min_present_minutes then
        v_auto_status := 'P';
    elsif v_total_minutes >= v_min_half_minutes then
        v_auto_status := 'H';
    else
        v_auto_status := 'A';
    end if;

    insert into daily_attendance (
        labor_id, department_id, date,
        first_login, last_logout, total_hours,
        auto_status, final_status, client_id, updated_at
    ) values (
        p_labor_id, v_department_id, p_date,
        v_first_login, v_last_logout, v_total_hours,
        v_auto_status, v_auto_status, v_client_id, now()
    )
    on conflict (labor_id, date)
    do update set
        first_login  = excluded.first_login,
        last_logout  = excluded.last_logout,
        total_hours  = excluded.total_hours,
        auto_status  = excluded.auto_status,
        final_status = case
            when daily_attendance.final_status in ('LP','LH','LA')
            then daily_attendance.final_status
            else excluded.auto_status
        end,
        updated_at = now();
end;
$$;


grant execute on function public.get_next_labor_id(), public.register_iqama(text), public.update_daily_attendance(text, date) to anon, authenticated;

-- 4. photos public again, old storage rules
update storage.buckets set public = true, file_size_limit = null, allowed_mime_types = null where id = 'punch-photos';
create policy "Allow upload" on storage.objects for insert to anon with check (bucket_id = 'punch-photos');
create policy "Allow view" on storage.objects for select to anon using (bucket_id = 'punch-photos');
create policy "Allow delete" on storage.objects for delete to anon using (bucket_id = 'punch-photos');

-- 5. other apps back, supervisors as before
do $$
declare r record;
begin
    for r in select table_name from information_schema.tables where table_schema = 'archive_other_apps' and table_type = 'BASE TABLE' and table_name <> 'supervisor_status_backup' loop
        execute format('alter table archive_other_apps.%I set schema public', r.table_name);
    end loop;
end $$;
grant all on all tables in schema public to anon, authenticated;
update public.users u set status = b.status from archive_other_apps.supervisor_status_backup b where b.id = u.id;
